// The retired home program — the single-adjustable-dumbbell exercises the app
// started with (see docs/home-dumbbell-program.md). They are no longer offered
// in the gym routine, but stay registered so every logged session, chart and
// personal record from the home days still resolves and renders.
//
// (Plank, Biceps Curl, Goblet Squat and Bulgarian Split Squat moved into the
// gym catalog under the same ids, so their history carries straight over.)

import type { ExerciseDef } from './exercises'

type HomeDef = Omit<ExerciseDef, 'retired'>

const HOME: readonly HomeDef[] = [
  {
    id: 'floor-press',
    name: 'Floor Press',
    muscle: 'Chest',
    slot: 'chest-press',
    sets: 3,
    kind: 'reps',
    repMin: 8,
    repMax: 12,
    startWeightKg: 8,
    perArm: true,
    equipment: 'home-dumbbell',
    formCue:
      'On your back, dumbbell at chest level, press straight up. Lower until your upper arm taps the floor, then drive up. The floor caps the range and protects the shoulder.',
  },
  {
    id: 'chest-flye',
    name: 'Chest Flye',
    muscle: 'Chest',
    slot: 'chest-stretch',
    sets: 3,
    kind: 'reps',
    repMin: 8,
    repMax: 12,
    startWeightKg: 5.5,
    perArm: true,
    equipment: 'home-dumbbell',
    formCue:
      'On your back, arm slightly bent and fixed at that angle. Open out wide toward the floor, feel the stretch across the chest, then squeeze back up over your chest. Light weight — this is a stretch movement, not a press.',
  },
  {
    id: 'overhead-press',
    name: 'Overhead Press',
    muscle: 'Shoulders',
    slot: 'shoulder-press',
    sets: 3,
    kind: 'reps',
    repMin: 8,
    repMax: 12,
    startWeightKg: 6.5,
    perArm: true,
    equipment: 'home-dumbbell',
    formCue:
      'From shoulder height, press to locked out overhead. Keep your ribs down and don’t lean back — the work should be in the shoulder, not the lower back.',
  },
  {
    id: 'lateral-raise',
    name: 'Lateral Raise',
    muscle: 'Shoulders',
    slot: 'shoulder-raise',
    sets: 3,
    kind: 'reps',
    repMin: 8,
    repMax: 12,
    startWeightKg: 3.5,
    perArm: true,
    equipment: 'home-dumbbell',
    formCue:
      'Raise the dumbbell out to the side up to shoulder height, leading with the elbow. No swinging or heaving — if you need momentum, the weight is too heavy. The side delt is small; keep it strict and light.',
  },
  {
    id: 'triceps-extension',
    name: 'Triceps Extension',
    muscle: 'Arms',
    slot: 'arm-triceps',
    sets: 3,
    kind: 'reps',
    repMin: 8,
    repMax: 12,
    startWeightKg: 9,
    perArm: false,
    equipment: 'home-dumbbell',
    holdNote: 'Both hands cupping one end of the dumbbell, behind your head.',
    formCue:
      'Both hands cupping one end of the dumbbell, held behind your head. Extend straight up, keeping the elbows pointing forward and still. Only the forearms move.',
  },
  {
    id: 'wrist-curl',
    name: 'Wrist Curl',
    muscle: 'Forearms',
    slot: 'forearm-flexor',
    sets: 3,
    kind: 'reps',
    repMin: 10,
    repMax: 15,
    startWeightKg: 4.5,
    perArm: true,
    equipment: 'home-dumbbell',
    formCue:
      'Forearm resting on your thigh, palm up, hand off the edge of the knee. Curl the weight up using only the wrist. Full range, controlled.',
  },
  {
    id: 'reverse-wrist-curl',
    name: 'Reverse Wrist Curl',
    muscle: 'Forearms',
    slot: 'forearm-extensor',
    sets: 3,
    kind: 'reps',
    repMin: 10,
    repMax: 15,
    startWeightKg: 2.5,
    perArm: true,
    equipment: 'home-dumbbell',
    formCue:
      'Same position as the wrist curl, palm down. Lift the back of the hand toward you. This is a weak movement — expect to use very little weight, and that’s correct.',
  },
  {
    id: 'weighted-crunch',
    name: 'Weighted Crunch',
    muscle: 'Core',
    slot: 'ab-crunch',
    sets: 3,
    kind: 'reps',
    repMin: 12,
    repMax: 15,
    startWeightKg: 5.5,
    perArm: false,
    equipment: 'home-dumbbell',
    holdNote: 'Hold the dumbbell on your chest.',
    formCue:
      'Hold the dumbbell on your chest. Crunch up, squeeze the abs hard at the top, lower with control. Don’t yank with the neck.',
  },
  {
    id: 'russian-twist',
    name: 'Russian Twist',
    muscle: 'Core',
    slot: 'ab-rotation',
    sets: 3,
    kind: 'reps',
    repMin: 14,
    repMax: 20,
    startWeightKg: 4.5,
    perArm: false,
    equipment: 'home-dumbbell',
    holdNote: 'Held at the chest. Count every touch as one rep (left + right = two).',
    formCue:
      'Lean back with feet off the floor, holding the dumbbell. Rotate from hip to hip, touching near the floor each side. Count every touch as one rep (so a left + right is two).',
  },
  {
    id: 'squeeze-press',
    name: 'Squeeze Press',
    muscle: 'Chest',
    slot: 'chest-press',
    sets: 3,
    kind: 'reps',
    repMin: 8,
    repMax: 12,
    startWeightKg: 8,
    perArm: false,
    equipment: 'home-dumbbell',
    holdNote: 'One dumbbell held vertically, squeezed between both palms.',
    formCue:
      'On your back, hold one dumbbell vertically, sandwiched between your palms at chest level. Press straight up while squeezing your palms together hard — the squeeze is what drives the chest. Lower under control.',
  },
  {
    id: 'dumbbell-pullover',
    name: 'Dumbbell Pullover',
    muscle: 'Chest',
    slot: 'chest-stretch',
    sets: 3,
    kind: 'reps',
    repMin: 8,
    repMax: 12,
    startWeightKg: 6.5,
    perArm: false,
    equipment: 'home-dumbbell',
    holdNote: 'Both hands cupping one end of the dumbbell.',
    formCue:
      'On your back, both hands cupping one end of the dumbbell over your chest, slight bend in the elbows. Lower it back over and behind your head until you feel the stretch, then pull it back over your chest. Light and controlled.',
  },
  {
    id: 'arnold-press',
    name: 'Arnold Press',
    muscle: 'Shoulders',
    slot: 'shoulder-press',
    sets: 3,
    kind: 'reps',
    repMin: 8,
    repMax: 12,
    startWeightKg: 6.5,
    perArm: true,
    equipment: 'home-dumbbell',
    formCue:
      'Start at shoulder height with your palm facing you. Press up while rotating the palm to face forward at the top; reverse on the way down. Ribs down, no leaning back.',
  },
  {
    id: 'front-raise',
    name: 'Front Raise',
    muscle: 'Shoulders',
    slot: 'shoulder-raise',
    sets: 3,
    kind: 'reps',
    repMin: 8,
    repMax: 12,
    startWeightKg: 3.5,
    perArm: true,
    equipment: 'home-dumbbell',
    formCue:
      'Raise the dumbbell straight out in front to shoulder height, arm almost straight. No swinging — control it up and down. Hits the front of the shoulder.',
  },
  {
    id: 'rear-delt-fly',
    name: 'Rear-Delt Fly',
    muscle: 'Shoulders',
    slot: 'shoulder-raise',
    sets: 3,
    kind: 'reps',
    repMin: 10,
    repMax: 15,
    startWeightKg: 3.5,
    perArm: true,
    equipment: 'home-dumbbell',
    formCue:
      'Hinge forward at the hips, back flat. With a slight, fixed elbow bend, raise the dumbbell out to the side until level with your back, squeezing the rear shoulder. Strict and light — great for shoulder balance.',
  },
  {
    id: 'hammer-curl',
    name: 'Hammer Curl',
    muscle: 'Arms',
    slot: 'arm-biceps',
    sets: 3,
    kind: 'reps',
    repMin: 8,
    repMax: 12,
    startWeightKg: 8,
    perArm: true,
    equipment: 'home-dumbbell',
    formCue:
      'Curl with a neutral grip — palm facing in, thumb up, like holding a hammer. No torso swing; lower under control. Builds the biceps and the brachialis underneath.',
  },
  {
    id: 'concentration-curl',
    name: 'Concentration Curl',
    muscle: 'Arms',
    slot: 'arm-biceps',
    sets: 3,
    kind: 'reps',
    repMin: 8,
    repMax: 12,
    startWeightKg: 6.5,
    perArm: true,
    equipment: 'home-dumbbell',
    formCue:
      'Seated, elbow braced against the inside of your thigh. Curl the dumbbell up with a hard squeeze at the top, lower slowly. Strict isolation — no momentum at all.',
  },
  {
    id: 'triceps-kickback',
    name: 'Triceps Kickback',
    muscle: 'Arms',
    slot: 'arm-triceps',
    sets: 3,
    kind: 'reps',
    repMin: 10,
    repMax: 15,
    startWeightKg: 5.5,
    perArm: true,
    equipment: 'home-dumbbell',
    formCue:
      'Hinge forward, upper arm pinned parallel to your torso and still. Extend the forearm straight back until the arm locks out, squeeze the triceps, return under control. Only the forearm moves.',
  },
  {
    id: 'single-arm-oh-ext',
    name: 'Single-Arm Overhead Extension',
    muscle: 'Arms',
    slot: 'arm-triceps',
    sets: 3,
    kind: 'reps',
    repMin: 8,
    repMax: 12,
    startWeightKg: 5.5,
    perArm: true,
    equipment: 'home-dumbbell',
    formCue:
      'One dumbbell in one hand overhead, upper arm vertical and still. Lower it behind your head, then extend straight up. Keep the elbow pointing forward, not flaring out.',
  },
  {
    id: 'behind-back-wrist-curl',
    name: 'Behind-the-Back Wrist Curl',
    muscle: 'Forearms',
    slot: 'forearm-flexor',
    sets: 3,
    kind: 'reps',
    repMin: 10,
    repMax: 15,
    startWeightKg: 5.5,
    perArm: true,
    equipment: 'home-dumbbell',
    formCue:
      'Stand holding the dumbbell behind your back, palm facing back, arm straight. Curl it up using only the wrist, then lower for a full stretch. Small range, strict.',
  },
  {
    id: 'reverse-curl',
    name: 'Reverse Curl',
    muscle: 'Forearms',
    slot: 'forearm-extensor',
    sets: 3,
    kind: 'reps',
    repMin: 10,
    repMax: 15,
    startWeightKg: 4.5,
    perArm: true,
    equipment: 'home-dumbbell',
    formCue:
      'Curl with a palm-down (overhand) grip, elbow tucked at your side. Lift to about chest height and lower slowly. Targets the top of the forearm and the brachioradialis — expect to use less than a normal curl.',
  },
  {
    id: 'weighted-situp',
    name: 'Weighted Sit-up',
    muscle: 'Core',
    slot: 'ab-crunch',
    sets: 3,
    kind: 'reps',
    repMin: 12,
    repMax: 15,
    startWeightKg: 5.5,
    perArm: false,
    equipment: 'home-dumbbell',
    holdNote: 'Hold the dumbbell on your chest.',
    formCue:
      'Full sit-up holding the dumbbell on your chest. Curl all the way up, then lower with control to the floor. Don’t yank with the neck or throw with the hips.',
  },
  {
    id: 'weighted-side-bend',
    name: 'Weighted Side Bend',
    muscle: 'Core',
    slot: 'ab-rotation',
    sets: 3,
    kind: 'reps',
    repMin: 12,
    repMax: 15,
    startWeightKg: 8,
    perArm: true,
    equipment: 'home-dumbbell',
    formCue:
      'Stand tall, dumbbell in one hand at your side. Bend sideways toward that hand, then pull straight back up using the opposite obliques. Full count one side, then switch. No leaning forward or back.',
  },
  {
    id: 'wood-chop',
    name: 'Wood Chop',
    muscle: 'Core',
    slot: 'ab-rotation',
    sets: 3,
    kind: 'reps',
    repMin: 12,
    repMax: 15,
    startWeightKg: 5.5,
    perArm: false,
    equipment: 'home-dumbbell',
    holdNote: 'Both hands; do the full count on one side, then the other.',
    formCue:
      'Both hands on the dumbbell. From low by one hip, sweep it diagonally up and across to above the opposite shoulder, rotating through the trunk, then back down. Full count one side, then switch.',
  },
  {
    id: 'side-plank',
    name: 'Side Plank',
    muscle: 'Core',
    slot: 'ab-core',
    sets: 3,
    kind: 'time',
    repMin: 0,
    repMax: 0,
    startWeightKg: 0,
    perArm: false,
    equipment: 'none',
    startSeconds: 20,
    timeIncrementSeconds: 10,
    holdNote: 'Hold each side for the target.',
    formCue:
      'On one forearm, body in a straight line, hips stacked and lifted. Brace the side abs and hold the target, then switch sides. Bodyweight only — the duration climbs.',
  },
  {
    id: 'hollow-hold',
    name: 'Hollow Hold',
    muscle: 'Core',
    slot: 'ab-core',
    sets: 3,
    kind: 'time',
    repMin: 0,
    repMax: 0,
    startWeightKg: 0,
    perArm: false,
    equipment: 'none',
    startSeconds: 20,
    timeIncrementSeconds: 10,
    formCue:
      'On your back, lower back pressed flat into the floor, arms and legs extended and lifted into a shallow “banana”. Hold and keep breathing. Higher arms/legs = easier, lower = harder.',
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    muscle: 'Legs',
    slot: 'leg-hinge',
    sets: 3,
    kind: 'reps',
    repMin: 10,
    repMax: 15,
    startWeightKg: 10,
    perArm: false,
    equipment: 'home-dumbbell',
    holdNote: 'One dumbbell held in both hands in front of the thighs.',
    formCue:
      'Hold one dumbbell in both hands in front of your thighs. Soft knees, push your hips back and lower the weight down your legs until you feel the hamstrings stretch, back flat. Drive the hips forward to stand tall. Hinge, don’t squat.',
  },
  {
    id: 'single-leg-rdl',
    name: 'Single-Leg RDL',
    muscle: 'Legs',
    slot: 'leg-hinge',
    sets: 3,
    kind: 'reps',
    repMin: 8,
    repMax: 12,
    startWeightKg: 6.5,
    perArm: true,
    equipment: 'home-dumbbell',
    formCue:
      'Dumbbell in one hand, stand on the opposite leg. Hinge at the hip and let the free leg float back as the weight lowers, back flat, until you feel the standing hamstring. Return to tall. Full count one side, then switch — great for a runner’s balance.',
  },
  {
    id: 'reverse-lunge',
    name: 'Reverse Lunge',
    muscle: 'Legs',
    slot: 'leg-lunge',
    sets: 3,
    kind: 'reps',
    repMin: 8,
    repMax: 12,
    startWeightKg: 8,
    perArm: true,
    equipment: 'home-dumbbell',
    formCue:
      'Dumbbell in one hand or held at your chest. Step one foot back and lower until both knees are about 90°, front shin vertical, then push through the front heel to stand. Full count one leg, then switch — easier on the knees than a forward lunge.',
  },
  {
    id: 'step-up',
    name: 'Step-up',
    muscle: 'Legs',
    slot: 'leg-lunge',
    sets: 3,
    kind: 'reps',
    repMin: 8,
    repMax: 12,
    startWeightKg: 8,
    perArm: true,
    equipment: 'home-dumbbell',
    formCue:
      'Dumbbell in one hand, one foot planted on a sturdy knee-height step. Drive through that heel to stand all the way up, then lower under control without pushing off the floor. Full count one leg, then switch.',
  },
  {
    id: 'calf-raise',
    name: 'Standing Calf Raise',
    muscle: 'Legs',
    slot: 'leg-calf',
    sets: 3,
    kind: 'reps',
    repMin: 12,
    repMax: 20,
    startWeightKg: 10,
    perArm: false,
    equipment: 'home-dumbbell',
    holdNote: 'One dumbbell held at your side; balls of the feet on the floor or a step.',
    formCue:
      'Hold one dumbbell at your side, balls of the feet on the floor or the edge of a step for more range. Rise up onto your toes as high as you can, pause at the top, lower slowly. Full range and a hard squeeze — key for durable running calves.',
  },
  {
    id: 'single-leg-calf-raise',
    name: 'Single-Leg Calf Raise',
    muscle: 'Legs',
    slot: 'leg-calf',
    sets: 3,
    kind: 'reps',
    repMin: 12,
    repMax: 20,
    startWeightKg: 6.5,
    perArm: true,
    equipment: 'home-dumbbell',
    formCue:
      'Balance on one foot, dumbbell in the same-side hand, other hand on a wall for balance. Rise onto the toes, pause, lower slowly. Full count one leg, then switch.',
  },
]

export const HOME_EXERCISES: readonly ExerciseDef[] = HOME.map((d) => ({
  ...d,
  retired: true,
}))
